# Changes here will be overwritten by Copier
_commit: v0.2.17
_src_path: gh:natescherer/postmodern-repo-copiertemplate
author_name: Nate Scherer
developer_platform: GitHub
github_org: ''
github_username: natescherer
license: MIT
lifecycle: Pre-Alpha
project_name: Postmodern Helm Deployment Copier Template
project_short_description: A Copier template for deploying Helm charts with full CI/CD.
project_type: Template
project_visibility: Public
project_website: ''
repo_actions: None
repo_name: postmodern-helm-deploy-copiertemplate
