name: Copier Source Template Update

on:
  schedule:
    - cron: "0 2 * * 1" # Every Monday at 2am
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Copier & Inject Dependencies
        run: |
          pipx install copier
          pipx inject copier -r .devcontainer/library/requirements.txt
      - name: Check if update is available
        continue-on-error: false
        id: check
        run: |
          echo "TBD"
      - name: Run update if available
        if: steps.check.outputs.has_changes == '1'
        run: |
          echo "TBD"
      - name: Create pull request
        if: steps.check.outputs.has_changes == '1'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: ${{ matrix.add-paths }}
          commit-message: ${{ matrix.commit-message }}
          branch: ${{ matrix.branch }}
          delete-branch: true
          branch-suffix: timestamp
          title: ${{ matrix.title }}
          body: |
            This is an autogenerated PR. ${{ matrix.body }}

            Copier has detected updates from the template repository.