name: Tests for PRs

on:
  pull_request_target:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Example Tests
        run: |
          FILE=README.md
          if [ -f "$FILE" ]; then
            echo "$FILE exists."
            echo "Also you should probably put one or more real checks relevant to your project here."
          else
            echo "$FILE missing!"
            exit 1
          fi
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          post-annotations: true
