name: All Contributors PR Merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'allcontributors[bot]' }}
    steps:
      - name: Enable auto-merge for AllContributors PRs
        run: |
          # Retry to work around "Base branch was modified." error.
          # Ref: https://github.com/cli/cli/issues/8092
          for i in {1..3}; do
            if gh pr merge --merge "$PR_URL"; then
              break
            fi
            if [[ $i -eq 3 ]]; then
              exit 1
            fi
            sleep 5
          done
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
