name: All Contributors PR Create

on:
  push:
    branches:
      - main

permissions:
  issues: write
  pull-requests: write

jobs:
  allcontributors_create_pr:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'allcontributors[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run All Contributors Auto Action
        uses: JoshuaKGoldberg/all-contributors-auto-action@v0.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
