name: Weekly Copier Template Update Check

on:
  schedule:
    - cron: "0 8 * * 0" # Runs every Sunday at 08:00 UTC
  workflow_dispatch: # Allows manual runs

jobs:
  copier-check-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures tags are checked out
      - name: Check for Copier Template Updates
        id: copier
        uses: natescherer/copier-action@v0
        with:
          subcommand: check-update
          answers-file: .config/copier-answers.yml
      - name: Notify if Update is Available
        if: steps.copier.outputs.update_available == 'true'
        uses: cstuder/apprise-ga@v3.1.0
        with:
          title: ${{ github.repository }} Template Update Available
          message: |
            Repository ${{ github.repository }} has a new template update available.

            Current version is ${{ steps.copier.outputs.current_version }}, latest version is ${{ steps.copier.outputs.latest_version }}.
        env:
          APPRISE_URL: ${{ secrets.APPRISE_URL }}
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
